[versions]
agconnect = "1.9.1.304"
agp = "8.9.1"
appcompat = "1.7.0"
appservice = "6.1.0.301"
appUpdateKtx = "2.1.0"
constraintlayout = "2.2.1"
coreKtx = "1.16.0"
dagger = "2.56.1"
fragmentKtx = "1.8.6"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.32"
preferenceKtx = "1.2.1"

[libraries]
# Android
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }

# Google
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }

# Dagger
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

# Huawei
appservice = { module = "com.huawei.hms:appservice", version.ref = "appservice" }
huawei-plugin = { module = "com.huawei.agconnect:agcp", version.ref = "agconnect" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-android-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }