[versions]
agconnect = "1.9.6.300"
agp = "9.3.2"
appcompat = "1.8.0"
appservice = "6.16.2.300"
appUpdateKtx = "2.1.0"
constraintlayout = "2.2.2"
coreKtx = "1.19.0"
dagger = "2.60.1"
fragmentKtx = "1.9.0"
ksp = "2.3.11"
preferenceKtx = "1.2.1"

[libraries]
# Android
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }

# Google
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }

# Dagger
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

# Huawei
appservice = { module = "com.huawei.hms:appservice", version.ref = "appservice" }
huawei-plugin = { module = "com.huawei.agconnect:agcp", version.ref = "agconnect" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }